name: flutter_share_example
description: Demonstrates how to use the flutter_share plugin.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  documents_picker: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_share:
    path: ../

flutter:

  uses-material-design: true
