name: flutter_share
description: Simple way to share message, links or files from your flutter app for Android and IOS (Enter to see some gifs).
version: 1.0.2
author: Lucas Britto <l_demello@hotmail.com>
homepage: https://github.com/lubritto/flutter_share

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.fluttershare
    pluginClass: FlutterSharePlugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"