name: flutter_share
description: Simple way to share message, links or files from your flutter app for Android and IOS (Enter to see some gifs).
version: 1.0.3
homepage: https://github.com/lubritto/flutter_share

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.fluttershare
        pluginClass: FlutterSharePlugin
      ios:
        pluginClass: FlutterSharePlugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"
  # Flutter versions prior to 1.12 did not support the
  # flutter.plugin.platforms map.
  flutter: ">=1.12.0 <2.0.0"