name: flutter_share
description: Simple way to share files from your flutter app
version: 0.0.5
author: Lucas Britto <l_demello@hotmail.com>
homepage: https://github.com/lubritto/flutter_share

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.fluttershare
    pluginClass: FlutterSharePlugin

environment:
  sdk: ">=2.1.0 <3.0.0"